#+LATEX_CLASS: doc
#+LATEX_CLASS_OPTIONS: [11pt]
#+LATEX_HEADER: \setminted{linenos}
#+OPTIONS: author:nil title:nil date:nil toc:nil


\title{QUPIT: QUasiadiabatic propagator Path Integral Toolkit}
\author{Ruofan Chen}
\maketitle
\tableofcontents

* A Review on QUAPI
In this chapter we give a review of the formalism of the QUAPI
cite:makarov1994-path,makri1995-numerical,segal2010-numerically.  Let
us consider a generic many-body system which can be modeled by a
finite system of interest coupled to a bath. Let $H(t)$ denote the
total Hamiltonian which can split into three parts:
\begin{equation}
H(t)=H_S(t)+H_B+H_{SB},
\end{equation}
where $H_S(t)$ is the Hamiltonian of the system of interest, $H_B$ is
the Hamiltonian of the bath and $H_{SB}$ represents the coupling
between the system and the bath. Here we consider the case where only
the system Hamiltonian $H_S(t)$ is time-dependent. Let $\rho(t)$ be
the total density matrix, then the time evolution of $\rho(t)$ is
given by
\begin{equation}
\rho(t)=U(t)\rho(0)U^{\dag}(t),
\end{equation}
where
\begin{equation}
U(t)=\mathrm{T}\exp[-i\int_0^t H(\tau)\dd{\tau}]
=\lim_{\delta t\to0}\prod_{t_i=0}^t e^{-iH(t_i)\delta_t}.
\end{equation}
Here $\mathrm{T}$ is the chronological ordering symbol, and the
product is understood in that we take the limit over all the
infinitesimal intervals $\delta t$. Therefore we can write the density
matrix $\rho(t)$ as
\begin{equation}
\rho(t)=\lim_{N\to\infty}e^{-iH(t_N)\delta t}\cdots e^{-iH(t_0)\delta t}
\rho(0)e^{iH(t_0)\delta t}\cdots e^{iH(t_N)\delta t}
\end{equation}
for $t_0=0$ and $\delta t=t/N$.

Now we introduce the reduced density matrix of the system
$\rho_B(t)=\Tr_B[\rho(t)]$, which is obtained by tracing the total
density matrix over the bath degrees of freedom, then the time
evolution of $\rho_B(t)$ is given by 
\begin{equation}
\rho_S(s'',s';t)=\Tr_B\bra{s''}
\lim_{N\to\infty}e^{-iH(t_N)\delta t}\cdots e^{-iH(t_1)\delta t}
\rho(0)e^{iH(t_1)\delta t}\cdots e^{iH(t_N)\delta t}\ket{s'}.
\end{equation}
For numerical evaluation we can employ finite $\delta t$ in the above
expression which approximates the evolution operator $U(t)$ into a
product of finite $N$ exponentials. Inserting the identity operator
$\int\ket{s}\bra{s}\dd{s}$ between every two exponentials and
relabeling $s'',s'$ as $s_N^+,s_N^-$ gives
\begin{equation}
\begin{split}
\rho(s_N^+,s_N^-;t)=&\int\dd{s}_0^+\cdots\dd{s_{N-1}^+}\int\dd{s_0^-}\cdots\dd{s_{N-1}^-}\\
&\quad\Tr_B[\mel{s_N^+}{e^{-iH(t_N)\delta t}}{s_{N-1}^+}\cdots
\mel{s_1^+}{e^{-iH(t_1)\delta t}}{s_0^+}\\
&\qquad\qquad\times\mel{s_0^+}{\rho(0)}{s_0^-}
\mel{s_0^-}{e^{iH(t_1)}\delta t}{s_1^-}\cdots
\mel{s_{N-1}^-}{e^{iH(t_N)\delta t}}{s_N^-}].
\end{split}
\end{equation}
The integrand in the above expression can be referred as the
``influence functional'' and we denote it by
$I(s_0^{\pm},\ldots,s_N^{\pm})$. The influence functional has an
important property which greatly simply the calculation: nonlocal
correlations in the influence functional decay exponentially under
certain conditions. For spin-boson model, finite temperature is
needed, and for spin-fermion model, finite chemical potential
difference or temperature is needed. This property enables practical
numerical calculation for the influence functional.

In the discretized form, $\rho(0)$ need to ``go'' through $N$ steps to
arrive at $\rho(t)$. Then nonlocal correlations with all length need
to be taken into consideration, which means the influence functional
can be written as a product of terms corresponding to different
correlation length $\Delta k$,
\begin{equation}
\label{eq:IF}
I(s_0^{\pm},\ldots,s_N^{\pm})=\prod_{k=0}^N I_0(s_k^{\pm})
\prod_{k=0}^{N-1}I_1(s_k^{\pm},s_{k+1}^{\pm})\cdots
\prod_{k=0}^{N-\Delta k}I_{\Delta k}(s_k^{\pm},s_{k+\Delta k}^{\pm})\cdots
I_N(s_0^{\pm},s_N^{\pm}).
\end{equation}
Now suppose the influence functional can be truncated beyond a memory
time $\tau_c=N_s\delta t$ for $N_s$ a positive integer, then we have
\begin{equation}
\label{eq:IFT}
I(s_0^{\pm},\ldots,s_N^{\pm})=\prod_{k=0}^N I_0(s_k^{\pm})
\prod_{k=0}^{N-1}I_1(s_k^{\pm},s_{k+1}^{\pm})\cdots
\prod_{k=0}^{N-\Delta k}I_{\Delta k}(s_k^{\pm},s_{k+\Delta k}^{\pm})\cdots
\prod_{k=0}^{N-N_s}I_{N_s}(s_0^{\pm},s_{N_s}^{\pm}).
\end{equation}
It is easy to see that \eqref{eq:IFT} becomes \eqref{eq:IF} when
$N_s\to\infty$, i.e., this approach becomes exact when
$\tau_c\to\infty$. In addition, we have
\begin{equation}
\begin{split}
I(s_0^{\pm},\ldots,s_N^{\pm})&=I(s_0^{\pm},\ldots,s_{N-1}^{\pm})
I_0(s_N^{\pm})\cdots I_{\Delta k}(s_{N-\Delta k},s_N^{\pm})\cdots
I_{N_s}(s_{N-N_s}^{\pm},s_N^{\pm})\\
&=I(s_0^{\pm},\ldots,s_{N-1}^{\pm})
\frac{I(s_{N-N_s}^{\pm},\ldots,s_{N}^{\pm})}{I(s_{N-N_s}^{\pm},\ldots,s_{N-1}^{\pm})},
\end{split}
\end{equation}
and recursively applying this expression yields
\begin{equation}
\label{eq:IFs}
I(s_0^{\pm},\ldots,s_N^{\pm})=I(s_0^{\pm}\ldots,s_{N_s}^{\pm})
I_s(s_1^{\pm},\ldots,s_{N_s+1}^{\pm})\cdots 
I_s(s_{N-N_s}^{\pm},\ldots,s_N^{\pm}),
\end{equation}
where
\begin{equation}
I_s(s_k^{\pm},\ldots,s_{k+N_s}^{\pm})=
\frac{I(s_k^{\pm},\ldots,s_{k+N_s}^{\pm})}{I(s_k^{\pm},\ldots,s_{k+N_s-1}^{\pm})}.
\end{equation}

To integrate \eqref{eq:IFs}, we define a multiple time system reduced
density matrix $\tilde{\rho}_S(s_k^{\pm},\ldots,s_{k+N_s-1})$ with an
initial condition $\tilde{\rho}_S(s_0^{\pm},\ldots,s_{N_s-1}^{\pm})=1$
for which all initial elements are one. Then the first evolution step
for \eqref{eq:IFs} is given by
\begin{equation}
\tilde{\rho}_S(s_1^{\pm},\ldots,s_{N_s}^{\pm})=
\int I(s_0^{\pm},\ldots,s_{N_s}^{\pm})\dd{s_0^{\pm}},
\end{equation}
and beyond the first step the evolution step is given by 
\begin{equation}
\tilde{\rho}_S(s_{k+1}^{\pm},\ldots,s_{k+N_s}^{\pm})=
\int\tilde{\rho}_S(s_k^{\pm},\ldots,s_{k+N_s-1}^{\pm})
I_s(s_k^{\pm},\ldots,s_{k+N_s}^{\pm})\dd{s_k^{\pm}}.
\end{equation}
Then the time-local $(t_k=k\delta t)$ reduced density matrix is
obtained by summing over all intermediate states for which
\begin{equation}
\rho_S(s_k^+,s_k^-;t_k)=\int\tilde{\rho}_S(s_{k-N_s+1},\ldots,s_k^{\pm})
\dd{s_{k}^{\pm}}\cdots\dd{s_{k-N_s+1}^{\pm}}.
\end{equation}

** Spin-Boson Model
The system Hamiltonian of the spin-boson model describes a two level
system for which
\begin{equation}
H_S(t)=\frac{1}{2}\bm{B}(t)\cdot\bm{\sigma},
\end{equation}
where $\bm{\sigma}=(\sigma_x,\sigma_y,\sigma_z)$ which is the Pauli
matrices vector and $\bm{B}(t)$ is the external field. The bath
Hamiltonian describes a collection of phonon modes for which
\begin{equation}
H_B=\sum_k\omega_kb_k^{\dag}b_k,
\end{equation}
where $b_k^{\dag}$ ($b_k$) creates (annihilates) a phonon with
frequency $\omega_k$. The system-bath coupling is taken to be
\begin{equation}
H_{SB}=\frac{1}{2}\sum_kV_k(\bm{n}\cdot\bm{\sigma})(b_k+b_k^{\dag}),
\end{equation}
where $\bm{n}$ is an unit vector with spherical angle $\theta,\phi$
for which $\bm{n}=(\sin\theta\cos\phi,\sin\theta\sin\phi,\cos\theta)$,
and
\begin{equation}
\bm{n}\cdot\bm{\sigma}=\sigma_x\sin\theta\cos\phi+
\sigma_y\sin\theta\sin\phi+\sigma_z\cos\theta.
\end{equation}
This unit vector $\bm{n}$ describes the system-bath coupling angle
$\theta,\phi$. The bath can be characterized by the spectral density
\begin{equation}
J(\omega)=\sum_kV_k^2\delta(\omega-\omega_k)=
\alpha\omega^s\Theta(\omega-\omega_c),
\end{equation}
where $\alpha$ is the control parameter, $\Theta$ is the heavy step
function and $\omega_c$ is the cutoff frequency of the phonon modes.
The exponential factor describes the type of bath: when $0<s<1$ we
have a sub-Ohmic form, when $s=1$ we have an Ohmic form, and when
$s>1$ we have a super-Ohmic form.

* Reference
\bibliographystyle{plainurl}
\bibliography{/home/crf/Nutstore/Literature/papers}
